'use strict';
const el=id=>document.getElementById(id);
const sets={math:[['6 × 7 = ?','42'],['8 × 4 = ?','32'],['9 × 3 = ?','27'],['5 × 8 = ?','40']]};
let player,apiPromise,pendingQuestion=false,currentQuestion,index=0,answered=0,correct=0,played=0,lastTime=null,generation=0;
function parseVideo(value){const v=value.trim();if(/^[A-Za-z0-9_-]{11}$/.test(v))return v;try{const u=new URL(v);const host=u.hostname.toLowerCase().replace(/^www\./,'');let id;if(host==='youtu.be')id=u.pathname.split('/')[1];else if(['youtube.com','m.youtube.com','youtube-nocookie.com'].includes(host)){id=u.searchParams.get('v');if(!id&&/^\/(embed|shorts|live)\//.test(u.pathname))id=u.pathname.split('/')[2];}return /^[A-Za-z0-9_-]{11}$/.test(id||'')?id:null;}catch{return null;}}
function parseStart(value){try{const u=new URL(value.trim());const raw=u.searchParams.get('t')||u.searchParams.get('start')||'';if(/^\d+$/.test(raw))return Number(raw);const m=/^(?:(\d+)h)?(?:(\d+)m)?(?:(\d+)s)?$/.exec(raw);return m?Number(m[1]||0)*3600+Number(m[2]||0)*60+Number(m[3]||0):0;}catch{return 0;}}
function loadAPI(){if(window.YT&&YT.Player)return Promise.resolve();if(apiPromise)return apiPromise;apiPromise=new Promise((resolve,reject)=>{window.onYouTubeIframeAPIReady=resolve;const script=document.createElement('script');script.src='https://www.youtube.com/iframe_api';script.onerror=()=>{apiPromise=null;reject(new Error('YouTube player could not load. Check your connection or browser restrictions.'));};document.head.append(script);});return apiPromise;}
function clearQuestion(){pendingQuestion=false;el('answer-form').hidden=true;el('resume').hidden=true;el('feedback').textContent='';el('waiting').hidden=false;played=0;lastTime=null;}
function updateScore(){el('score').textContent=`Session practice: ${answered} answered · ${correct} correct`;}
function askQuestion(){if(!player||pendingQuestion)return;player.pauseVideo();pendingQuestion=true;const list=sets[el('question-set').value];currentQuestion=list[index++%list.length];el('question').textContent=currentQuestion[0];el('answer').value='';el('answer-form').hidden=false;el('waiting').hidden=true;el('resume').hidden=false;el('feedback').textContent='';el('player-status').textContent='Practice break. You may answer or continue with the YouTube controls.';el('answer').focus({preventScroll:true});}
el('video-form').addEventListener('submit',async event=>{event.preventDefault();const id=parseVideo(el('video-url').value);const startSeconds=parseStart(el('video-url').value);if(!id){el('player-status').textContent='Enter a valid YouTube video URL or its 11-character ID.';return;}if(!el('embed-consent').checked)return;const request=++generation;el('player-status').textContent='Loading the YouTube player…';clearQuestion();try{await loadAPI();if(request!==generation)return;if(player){player.cueVideoById({videoId:id,startSeconds});el('player-status').textContent='Video selected. Press Play in the YouTube player.';}else{player=new YT.Player('player',{videoId:id,width:'100%',height:'100%',host:'https://www.youtube-nocookie.com',playerVars:{start:startSeconds,playsinline:1,autoplay:0,controls:1,origin:location.origin},events:{onReady:()=>{el('player-status').textContent='Video selected. Press Play in the YouTube player.';},onStateChange:e=>{lastTime=null;if(e.data===YT.PlayerState.PLAYING){if(pendingQuestion)clearQuestion();el('player-status').textContent='Playing. Independent practice follows the selected interval.';}else if(e.data===YT.PlayerState.ENDED){el('player-status').textContent='Video finished. Choose another video or clear this session.';}},onError:e=>{el('player-status').textContent=`YouTube cannot play this video here (error ${e.data}). Choose another link; restrictions are not bypassed.`;}}});}}catch(error){el('player-status').textContent=error.message;}});

el('answer-form').addEventListener('submit',event=>{event.preventDefault();if(!pendingQuestion)return;const value=el('answer').value.trim().toLowerCase();if(!value)return;answered++;const ok=value===currentQuestion[1];if(ok){correct++;clearQuestion();el('feedback').textContent='Correct. Resuming the video.';updateScore();if(player)player.playVideo();return;}el('feedback').textContent=`The sample answer is ${currentQuestion[1]}. You can continue the video.`;el('answer-form').hidden=true;updateScore();});
el('resume').addEventListener('click',()=>{clearQuestion();if(player)player.playVideo();});
el('reset').addEventListener('click',()=>{answered=correct=index=0;clearQuestion();el('answer').value='';currentQuestion=null;updateScore();el('player-status').textContent='Temporary question progress cleared.';});
el('question-set').addEventListener('change',()=>{index=0;clearQuestion();});el('interval').addEventListener('change',()=>{played=0;lastTime=null;});
setInterval(()=>{if(!player||typeof player.getPlayerState!=='function'||pendingQuestion||player.getPlayerState()!==YT.PlayerState.PLAYING){lastTime=null;return;}const now=player.getCurrentTime();if(lastTime!==null){const delta=now-lastTime;if(delta>0&&delta<2)played+=delta;}lastTime=now;const seconds=Number(el('interval').value);if(seconds>0&&played>=seconds)askQuestion();},500);

// Agreement is session-only; no cookies, consent identifiers or stored answers.
const gatedControls=['question-set','interval','video-url'];
function gateDemo(){const agreed=el('embed-consent').checked;gatedControls.forEach(id=>{el(id).disabled=!agreed;});el('video-form').querySelector('button[type=submit]').disabled=!agreed;if(!agreed){if(player||apiPromise){generation++;if(player)player.destroy();location.reload();}}}
el('embed-consent').addEventListener('change',gateDemo);
el('withdraw').addEventListener('click',()=>{generation++;if(player)player.destroy();location.reload();});
el('embed-consent').checked=false;gateDemo();
